export const CONTRIBUTORS_COUNT_REQUESTED = 'CONTRIBUTORS_COUNT_REQUESTED';
export const CONTRIBUTORS_COUNT_SUCCEEDED = 'CONTRIBUTORS_COUNT_SUCCEEDED';
export const CONTRIBUTORS_COUNT_FAILED = 'CONTRIBUTORS_COUNT_FAILED';

export const fetchContributorsCount = () => ({
  type: CONTRIBUTORS_COUNT_REQUESTED,
});
